version: "3.4"

services:
  python-hello-world-service:
    container_name: python-hello-world-service
    build:
      context: .
      dockerfile: backend-services/loki-grafana-stack/python/hello-world-service/Dockerfile
    depends_on:
      - "loki"
      - "grafana"
    ports:
      - "5003:80/tcp"
    environment:
      LOKI_URL: http://loki/loki/api/v1/push
    restart: on-failure

  rust-hello-world-service:
    container_name: rust-hello-world-service
    build:
      context: .
      dockerfile: backend-services/loki-grafana-stack/rust/hello-world-service/Dockerfile
    depends_on:
      - "loki"
      - "grafana"
    ports:
      - "5004:80/tcp"
    environment:
      LOKI_URL: http://loki/loki/api/v1/push
    restart: on-failure

  loki:
    image: grafana/loki:2.9.0
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - loki_network

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    networks:
      - loki_network

networks:
  loki_network:
