version: '3'
services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"
      - "6831:6831/udp"
      - "5778:5778"
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411
