version: '3.4'

services:
  csharp-hello-world-service:
    container_name: csharp-hello-world-service
    build:
      context: .
      dockerfile: backend-services/prometheus-grafana-stack/c#/HelloWorldService/Dockerfile
    depends_on:
      - "prometheus"
      - "grafana"
    ports:
      - "5001:80/tcp"
      - "9102:9102/tcp"
    restart: on-failure
  
  go-hello-world-service:
    container_name: go-hello-world-service
    build:
      context: .
      dockerfile: backend-services/prometheus-grafana-stack/go/hello-world-service/Dockerfile
    depends_on:
      - "prometheus"
      - "grafana"
    ports:
      - "5002:80/tcp"
    restart: on-failure

  python-hello-world-service:
    container_name: python-hello-world-service
    build:
      context: .
      dockerfile: backend-services/prometheus-grafana-stack/python/hello-world-service/Dockerfile
    depends_on:
      - "prometheus"
      - "grafana"
    ports:
      - "5003:80/tcp"
    restart: on-failure

  # monitoring services
  grafana:
    container_name: grafana
    image: grafana/grafana:master
    ports:
      - "3000:3000"
    # volumes: # Within Docker enabled in VirtualBox, deactivate or comment out the lines related to volume mounting. Specifically, this line and the subsequent two lines
    #   - ./grafana/provisioning/datasources/prometheus_ds.yml:/etc/grafana/provisioning/datasources/prometheus_ds.yml
    #   - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
    depends_on:
      - "prometheus"
    healthcheck:
      test: wget -q --tries=1 -O- http://localhost:3000/
      interval: 3s
      timeout: 3s
      retries: 10
      start_period: 10s

  prometheus:
    image: prom/prometheus
    container_name: prometheus-server
    ports:
      - 9090:9090
    # volumes: # Within Docker enabled in VirtualBox, deactivate or comment out the lines related to volume mounting. Specifically, this line and the subsequent line
    #   - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro 
    healthcheck:
      test: wget -q --tries=1 -O- http://localhost:9090/
      interval: 3s
      timeout: 3s
      retries: 10
      start_period: 10s